### ISSUE TITLE
🛑 esm.sh is down

### ISSUE THREAD

**Issue by azu** [azu/npmcdn-upptime#12]
In [`dbe2e06`](https://github.com/azu/npmcdn-upptime/commit/dbe2e06c90ce4afe76cc90bbb0575df858f4f87f
), esm.sh (https://esm.sh/) was **down**:
- HTTP code: 500
- Response time: 102 ms

**Comment by ije** [comment]
@azu this has been fixed, can you please close? thanks

**Comment by azu** [comment]
Thanks for letting me know.
